import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire('/Users/devaansh28/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json');
const {chromium}=require('playwright');
const out=path.resolve('lab');await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const results=[];
async function context(options={}){const c=await browser.newContext({viewport:{width:1440,height:1000},...options});await c.addInitScript(()=>{Element.prototype.requestPointerLock=()=>Promise.reject(new Error('Disabled for QA'));Element.prototype.setPointerCapture=()=>{};Element.prototype.releasePointerCapture=()=>{};Document.prototype.exitPointerLock=()=>{};});return c;}
const ctx=await context();const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>errors.push(r.url()+': '+r.failure()?.errorText));
// Dialog close is an asynchronous browser event; wait for its privacy cleanup.
const originalPress=p.keyboard.press.bind(p.keyboard);p.keyboard.press=async(...args)=>{const wasRegistration=await p.locator('#registration-dialog').isVisible();await originalPress(...args);if(args[0]==='Escape'&&wasRegistration)await p.waitForFunction(()=>document.querySelector('#guest-name').value==='');};
await p.goto('http://localhost:4500');await p.evaluate(()=>document.fonts.ready);await p.waitForSelector('html.sc-ready');
await p.waitForTimeout(1800);await p.screenshot({path:path.join(out,'desktop-hero.png')});
for(const id of ['experience','tracks','speakers','editions','partners','involved','join']){await p.locator('#'+id).scrollIntoViewIfNeeded();await p.waitForTimeout(750);await p.screenshot({path:path.join(out,'desktop-'+id+'.png')});}
await p.locator('[data-track=Blockchain]').click();await p.locator('[data-track=Security]').click();assert.equal(await p.locator('#interest-count').textContent(),'2 interests selected');await p.reload();assert.equal(await p.locator('[data-track=Blockchain]').getAttribute('aria-pressed'),'true');results.push('Track selection and reload persistence');
await p.locator('#tracks').scrollIntoViewIfNeeded();await p.waitForTimeout(300);await p.screenshot({path:path.join(out,'desktop-passport.png')});
await p.locator('#speaker-search').fill('nadja');assert.equal(await p.locator('.speaker-card:visible').count(),1);await p.locator('[data-speaker=nadja]').click();assert.equal(await p.locator('#profile-name').textContent(),'Nadja Bester');await p.screenshot({path:path.join(out,'speaker-profile.png')});await p.keyboard.press('Escape');assert.equal(await p.locator('#profile-dialog').isVisible(),false);await p.locator('#speaker-search').fill('no-such-speaker');assert.equal(await p.locator('#speaker-empty').isVisible(),true);await p.locator('#speaker-search').fill('');await p.locator('#more-speakers').click();assert.equal(await p.locator('.speaker-card:visible').count(),6);await p.locator('#more-speakers').click();results.push('Speaker search, empty state, profile dialog, Escape, expanded directory');
await p.locator('[data-location=dubai]').click();assert.equal(await p.locator('.event-card:visible').count(),1);await p.locator('[data-location=india]').click();assert.equal(await p.locator('.event-card:visible').count(),2);await p.locator('[data-location=all]').click();await p.locator('#events-next').click();await p.waitForTimeout(550);assert.ok(await p.locator('.event-rail').evaluate(el=>el.scrollLeft)>100);results.push('Event location filters and rail navigation');
await p.locator('[data-role=founders]').click();await p.locator('#role-route').click();assert.equal(await p.locator('[data-track=DAOs]').getAttribute('aria-pressed'),'true');await p.locator('[data-role=founders]').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('[data-role=investors]').getAttribute('aria-selected'),'true');results.push('Role routes and arrow-key tabs');
await p.locator('#passport-dock').click();await p.locator('#registration-next').click();assert.equal(await p.locator('#role-error').isVisible(),true);await p.locator('input[value=Builder]').check();await p.screenshot({path:path.join(out,'registration-role.png')});await p.locator('#registration-next').click();await p.locator('#guest-name').fill('Alex Morgan');await p.locator('#guest-email').fill('alex@example.com');await p.locator('#preview-consent').check();await p.screenshot({path:path.join(out,'registration-details.png')});await p.locator('#registration-step-two button[type=submit]').click();assert.equal(await p.locator('#registration-success').isVisible(),true);assert.match(await p.locator('#success-interests').textContent(),/Blockchain/);await p.screenshot({path:path.join(out,'registration-passport.png')});const dl=p.waitForEvent('download');await p.locator('#download-passport').click();const download=await dl;await download.saveAs(path.join(out,'test-passport.txt'));const content=await fs.readFile(path.join(out,'test-passport.txt'),'utf8');assert.match(content,/Alex Morgan/);assert.match(content,/not a ticket/);await p.keyboard.press('Escape');assert.equal(await p.locator('#guest-name').inputValue(),'');assert.ok(!await p.evaluate(()=>JSON.stringify(localStorage).includes('Alex Morgan')));results.push('Three-step registration, validation, interest carryover, download contents, PII clearing');
const themeBefore=await p.locator('body').evaluate(e=>e.classList.contains('light'));await p.locator('.theme-toggle').click();assert.equal(await p.locator('body').evaluate(e=>e.classList.contains('light')),!themeBefore);await p.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await p.screenshot({path:path.join(out,'desktop-alternate-theme.png')});await p.locator('.theme-toggle').click();await p.screenshot({path:path.join(out,'desktop-light.png')});
const broken=await p.locator('img').evaluateAll(imgs=>imgs.filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src));assert.deepEqual(broken,[]);results.push('Image loading');
await p.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await p.mouse.move(800,400);await p.screenshot({path:path.join(out,'pointer-a.png')});await p.mouse.move(1380,150);await p.screenshot({path:path.join(out,'pointer-b.png')});
for(const [name,width,height,reduced]of [['mobile',390,844,false],['compact',360,640,false],['tablet',768,1024,false],['reduced',1440,1000,true]]){const c=await context({viewport:{width,height},reducedMotion:reduced?'reduce':'no-preference'});const q=await c.newPage();await q.goto('http://localhost:4500');await q.evaluate(()=>document.fonts.ready);await q.waitForTimeout(350);const overflow=await q.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`${name} horizontal overflow`);await q.screenshot({path:path.join(out,name+'-hero.png')});for(const id of ['tracks','speakers','join']){await q.locator('#'+id).scrollIntoViewIfNeeded();await q.waitForTimeout(700);await q.screenshot({path:path.join(out,name+'-'+id+'.png')});}if(width<800){await q.locator('.menu-toggle').click();assert.equal(await q.locator('#mobile-nav').isVisible(),true);await q.keyboard.press('Escape');assert.equal(await q.locator('#mobile-nav').isVisible(),false);await q.locator('.closing .join-button').click();await q.locator('input[value=Explorer]').check();await q.locator('#registration-next').click();await q.locator('#guest-name').fill('Alex');await q.locator('#guest-email').fill('alex@example.com');await q.locator('#preview-consent').check();await q.locator('#registration-step-two button[type=submit]').click();assert.equal(await q.locator('#registration-success').isVisible(),true);await q.screenshot({path:path.join(out,name+'-registration.png')});}results.push(`${name} layout, overflow and interactions`);await c.close();}
const noJS=await context({javaScriptEnabled:false});const nq=await noJS.newPage();await nq.goto('http://localhost:4500');assert.equal(await nq.locator('#registration-form').getAttribute('method'),'dialog');assert.equal(await nq.locator('h1').isVisible(),true);results.push('No-JavaScript content and non-GET form fallback');await noJS.close();
await fs.writeFile(path.join(out,'functional-results.json'),JSON.stringify({passed:results,errors,broken},null,2));console.log(JSON.stringify({passed:results,errors,broken},null,2));await browser.close();
